#maths 
print("In this programe only mean fuction avilable")
print("hello class ")
print("this is your maths tutor bot")
print("statistics bassed formula solution ")
print("question type like : mean:")
print("so, put the value of marks ")
marks1 = input("put the 1st value : ")
marks2 = input("put the 2nd value : ")
marks3 = input("put the 3rd value : ")
marks4 = input("put the 4th value : ")
marks5 = input("put the 5th value : ")
marks6 = input("put the 6th value : ")
print("ok 😁 so, let's take next step")
print("this bot automatically find the value of xI")
xi1 = (int(marks1) / int(2))
print(xi1)
xi2  = (int(marks2) / int(2))
print(xi2)
xi3 = (int(marks3) / int(2))
print(xi3)
xi4 = (int(marks4) / int(2))
print(xi4)
xi5 = (int(marks5) / int(2))
print(xi5)
xi6 = (int(marks6) / int(2))
print(xi6)
print("progress done 🙃")
#put the value of (fi)
print("put the value of fI 👇")
fi1 = input("first value : ")
fi2 = input("second value : ")
fi3 = input("third value : ")
fi4 = input("fourth value : ")
fi5 = input("fifth value : ")
fi6 = input("sixth  value : ")
print("this bot automatically calculate total value of fi series")
print("total value 👇")
print(int(fi1)+int(fi2)+ int(fi3)+ int(fi4)+ int(fi5)+ int(fi6))
print("bot automatically find the value of fixi")
print("This bot automatically find the value of fixi")
import decimal
decimal1=decimal.Decimal(fi1)*decimal.Decimal(xi1)
print(decimal1)
decimal2=decimal.Decimal(fi2)*decimal.Decimal(xi2)
print(decimal2)
decimal3=decimal.Decimal(fi3)*decimal.Decimal(xi3)
print(decimal3)
decimal4=decimal.Decimal(fi4)*decimal.Decimal(xi4)
print(decimal4)
decimal5=decimal.Decimal(fi5)*decimal.Decimal(xi5)
print(decimal5)
decimal6=decimal.Decimal(fi6)*decimal.Decimal(xi6)
print(decimal6)
print("bot automatically calulate total of fixi series")
print("total value of fixi : 👇")
print(decimal1+decimal2+decimal3+decimal4+decimal5+decimal6)
print("i hope this bot helping you perfectly")
print("find mean : ")
fixi8 = input("enter the value of fixi : ")
fi9 = input("enter the value of fi : ")
print("total value of mean")
print(int(fixi8)/ int(fi9))
print("program finished 😄")
